services:
  app:
    image: node:20.14.0-slim
    container_name: dp-app
    ports:
      - "13000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "cd dp-app && npm install && npm run start"